# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Python application

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: 3.8
    - name: install
      run: |
        python -m pip install pipenv
        python -m pipenv install --deploy
    - name: checks
      run: |
        # stop the build if there are Python syntax errors or undefined names
        python -m pipenv run format
        python -m pipenv run lint
        python -m pipenv run typecheck
